In [117]:
import numpy as np
import pandas as pd

In [118]:
df = pd.read_csv('/content/drive/MyDrive/CP4/datasets/Colon.csv')

In [119]:
df.head()

H55933     R39465   R39465.1     R85482     U14973     R02593  \
0  8589.4160  5468.2407  4263.4077  4064.9358  1997.8930  5282.3250   
1  9164.2540  6719.5293  4883.4487  3718.1590  2015.2214  5569.9070   
2  3825.7050  6970.3613  5369.9688  4705.6500  1166.5536  1572.1678   
3  6246.4487  7823.5340  5955.8350  3975.5642  2002.6132  2130.5430   
4  3230.3286  3694.4500  3400.7400  3463.5857  2181.4202  2922.7820   

      T51496     H80240     T65938     T55131  ...    R70790     L11706  \
0  2169.7200  2773.4211  7526.3860  4607.6763  ...  67.56125  259.91250   
1  3849.0588  2793.3875  7017.7340  4802.2524  ...  92.23875   96.27625   
2  1325.4025  1472.2587  3296.9512  2786.5820  ...  82.71500   31.10250   
3  1531.1425  1714.6312  3869.7850  4989.4070  ...  41.68375    5.92500   
4  2069.2463  2948.5750  3303.3710  3109.4130  ...  76.60375  161.35000   

      T90549    D17390     M33210     H18490     H40891    R77780    T49647  \
0  138.89874  88.23250   39.66786   67.82875   75.67750  83.52250  28.70125   
1  150.59000  82.23750   85.03333  152.19500  186.56750  44.47250  16.77375   
2  193.92000  76.97250  224.62024   31.22500   42.65625  16.09250  15.15625   
3  183.00626  74.52875   67.71072   48.33875   42.52000  49.98250  16.08500   
4   61.70125  54.56375  223.35953   73.09875   57.59875   7.48875  31.81250   

    class  
0   Tumor  
1  Normal  
2   Tumor  
3  Normal  
4   Tumor  

[5 rows x 2001 columns]

In [120]:
y = y = df['class'].map({'Tumor': 1, 'Normal': 0})

In [121]:
X = df.drop(columns=['class'])
X.head()

H55933     R39465   R39465.1     R85482     U14973     R02593  \
0  8589.4160  5468.2407  4263.4077  4064.9358  1997.8930  5282.3250   
1  9164.2540  6719.5293  4883.4487  3718.1590  2015.2214  5569.9070   
2  3825.7050  6970.3613  5369.9688  4705.6500  1166.5536  1572.1678   
3  6246.4487  7823.5340  5955.8350  3975.5642  2002.6132  2130.5430   
4  3230.3286  3694.4500  3400.7400  3463.5857  2181.4202  2922.7820   

      T51496     H80240     T65938     T55131  ...     X67699    R70790  \
0  2169.7200  2773.4211  7526.3860  4607.6763  ...   99.11072  67.56125   
1  3849.0588  2793.3875  7017.7340  4802.2524  ...  126.78929  92.23875   
2  1325.4025  1472.2587  3296.9512  2786.5820  ...  151.87738  82.71500   
3  1531.1425  1714.6312  3869.7850  4989.4070  ...  152.59525  41.68375   
4  2069.2463  2948.5750  3303.3710  3109.4130  ...  126.46429  76.60375   

      L11706     T90549    D17390     M33210     H18490     H40891    R77780  \
0  259.91250  138.89874  88.23250   39.66786   67.82875   75.67750  83.52250   
1   96.27625  150.59000  82.23750   85.03333  152.19500  186.56750  44.47250   
2   31.10250  193.92000  76.97250  224.62024   31.22500   42.65625  16.09250   
3    5.92500  183.00626  74.52875   67.71072   48.33875   42.52000  49.98250   
4  161.35000   61.70125  54.56375  223.35953   73.09875   57.59875   7.48875   

     T49647  
0  28.70125  
1  16.77375  
2  15.15625  
3  16.08500  
4  31.81250  

[5 rows x 2000 columns]

In [122]:
new_columns = [i for i in range (2000)]
X.rename(columns=dict(zip(X.columns, new_columns)), inplace=True)
X.head()

0          1          2          3          4          5     \
0  8589.4160  5468.2407  4263.4077  4064.9358  1997.8930  5282.3250   
1  9164.2540  6719.5293  4883.4487  3718.1590  2015.2214  5569.9070   
2  3825.7050  6970.3613  5369.9688  4705.6500  1166.5536  1572.1678   
3  6246.4487  7823.5340  5955.8350  3975.5642  2002.6132  2130.5430   
4  3230.3286  3694.4500  3400.7400  3463.5857  2181.4202  2922.7820   

        6          7          8          9     ...       1990      1991  \
0  2169.7200  2773.4211  7526.3860  4607.6763  ...   99.11072  67.56125   
1  3849.0588  2793.3875  7017.7340  4802.2524  ...  126.78929  92.23875   
2  1325.4025  1472.2587  3296.9512  2786.5820  ...  151.87738  82.71500   
3  1531.1425  1714.6312  3869.7850  4989.4070  ...  152.59525  41.68375   
4  2069.2463  2948.5750  3303.3710  3109.4130  ...  126.46429  76.60375   

        1992       1993      1994       1995       1996       1997      1998  \
0  259.91250  138.89874  88.23250   39.66786   67.82875   75.67750  83.52250   
1   96.27625  150.59000  82.23750   85.03333  152.19500  186.56750  44.47250   
2   31.10250  193.92000  76.97250  224.62024   31.22500   42.65625  16.09250   
3    5.92500  183.00626  74.52875   67.71072   48.33875   42.52000  49.98250   
4  161.35000   61.70125  54.56375  223.35953   73.09875   57.59875   7.48875   

       1999  
0  28.70125  
1  16.77375  
2  15.15625  
3  16.08500  
4  31.81250  

[5 rows x 2000 columns]

## T = 0.7

In [123]:
columns = [4, 5, 28, 48, 65, 87, 99, 109, 118, 145, 148, 150, 152, 176, 182, 187, 191, 196, 205, 211, 227, 233, 250, 259, 260, 261, 262, 267, 268, 278, 284, 285, 303, 349, 353, 363, 376, 377, 387, 412, 436, 443, 455, 459, 466, 467, 473, 487, 494, 499, 503, 504, 515, 516, 522, 533, 545, 553, 557, 558, 559, 563, 564, 589, 605, 621, 629, 632, 640, 663, 672, 675, 680, 683, 697, 701, 714, 723, 725, 736, 738, 739, 750, 758, 764, 770, 782, 787, 799, 806, 809, 829, 835, 838, 855, 875, 877, 882, 900, 905, 907, 909, 917, 919, 931, 942, 958, 962, 983, 987, 996, 1007, 1009, 1013, 1015, 1023, 1024, 1041, 1049, 1051, 1057, 1063, 1076, 1077, 1082, 1086, 1103, 1107, 1145, 1152, 1162, 1183, 1207, 1216, 1225, 1235, 1239, 1240, 1241, 1247, 1263, 1266, 1267, 1281, 1282, 1303, 1307, 1311, 1317, 1320, 1323, 1324, 1339, 1350, 1354, 1363, 1371, 1380, 1381, 1386, 1387, 1398, 1407, 1410, 1436, 1444, 1450, 1451, 1463, 1464, 1469, 1481, 1490, 1491, 1494, 1499, 1504, 1515, 1519, 1521, 1535, 1547, 1551, 1556, 1557, 1569, 1578, 1580, 1584, 1586, 1591, 1610, 1613, 1625, 1636, 1643, 1648, 1654, 1670, 1674, 1678, 1679, 1682, 1713, 1735, 1737, 1741, 1742, 1746, 1747, 1750, 1760, 1762, 1769, 1772, 1781, 1784, 1785, 1790, 1794, 1796, 1809, 1810, 1816, 1818, 1821, 1827, 1829, 1852, 1861, 1869, 1872, 1885, 1892, 1894, 1899, 1900, 1904, 1908, 1919, 1920, 1928, 1929, 1942, 1953, 1954, 1962, 1971, 1975, 1978, 1979, 1987, 1990, 1992, 1999]

In [124]:
X07 = X[columns]

In [125]:
len(X07.columns)

255

## Standarizing the data

In [126]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score



# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X07, y, test_size=0.2, random_state=42, stratify=y)

# Standardize the features (important for regularization methods)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [127]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import accuracy_score

# Create the Lasso model
lasso = Lasso()

# Set up a grid of hyperparameters to search
param_grid = {'alpha': [0.001, 0.01, 0.1, 1.0, 10.0]}

# Use GridSearchCV to find the best hyperparameters
grid_search = GridSearchCV(lasso, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train_scaled, y_train)

# Get the best hyperparameters
best_alpha = grid_search.best_params_['alpha']

# Fit the Lasso model with the best hyperparameters on the entire training set
lasso_best = Lasso(alpha=best_alpha)
lasso_best.fit(X_train_scaled, y_train)

# Identify the selected features
selected_features_lasso_07 = X07.columns[lasso_best.coef_ != 0]

# Evaluate the model on the test set
y_pred = lasso_best.predict(X_test_scaled)
y_pred_binary = (lasso_best.predict(X_test_scaled) > 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred_binary)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)


# Print results
print("Best alpha:", best_alpha)
print("Selected Features:", selected_features_lasso_07)
print("Test Accuracy:", accuracy)
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.183e-03, tolerance: 8.667e-04
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.488e-03, tolerance: 8.974e-04
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.304e-03, tolerance: 9.231e

Best alpha: 0.1
Selected Features: Int64Index([376, 443, 466, 589, 697, 764, 1041, 1247, 1324, 1869, 1992], dtype='int64')
Test Accuracy: 0.8461538461538461
Mean Squared Error (MSE): 0.1454154027809028
R-squared (R2): 0.3856199232506857


## SVM-RFE

In [128]:
from sklearn.svm import SVC
from sklearn.feature_selection import RFE
from sklearn.datasets import make_classification
from sklearn.model_selection import StratifiedKFold
from sklearn.pipeline import Pipeline

# Create an SVM model
svm_model = SVC(kernel='linear')

# Create a pipeline with RFE and SVM
pipeline = Pipeline([
    ('feature_selection', RFE(svm_model)),
    ('classification', svm_model)
])

# Set the range of features to select
n_features_range = list(range(20, 50))  # Adjust the range based on your dataset

# Create a parameter grid
param_grid = {
    'feature_selection__n_features_to_select': n_features_range
}

# Perform cross-validated grid search
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)  # Adjust the number of splits as needed
grid_search = GridSearchCV(pipeline, param_grid=param_grid, cv=cv, scoring='accuracy')
grid_search.fit(X_train_scaled, y_train)

# Print the results
print("Best number of features:", grid_search.best_params_['feature_selection__n_features_to_select'])
print("Best cross-validated accuracy:", grid_search.best_score_)

# Use the best number of features from the grid search
n_best_features = grid_search.best_params_['feature_selection__n_features_to_select']

# Create an SVM model with RFE using the best number of features
final_svm_model = SVC(kernel='linear')
final_rfe = RFE(final_svm_model, n_features_to_select=n_best_features)

# Fit the final model on the training set
final_rfe.fit(X_train_scaled, y_train)
# Get the selected features
selected_features_rfe_07 = X07.columns[final_rfe.support_]
# Make predictions on the test set
y_pred = final_rfe.predict(X_test_scaled)

# Compute and print the test accuracy
test_accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", test_accuracy)
print("Selected Features:", n_best_features)
print(f"Mean Squared Error (MSE): {mse}")

Best number of features: 22
Best cross-validated accuracy: 0.8133333333333335
Test Accuracy: 0.5384615384615384
Selected Features: 22
Mean Squared Error (MSE): 0.1454154027809028


## T=0.75

In [129]:
columns = [10, 17, 28, 29, 34, 48, 65, 71, 78, 109, 116, 117, 131, 148, 149, 150, 151, 152, 159, 176, 186, 191, 227, 230, 233, 250, 251, 257, 258, 259, 260, 261, 262, 267, 278, 284, 285, 301, 303, 314, 316, 348, 353, 356, 359, 376, 383, 384, 385, 390, 396, 403, 412, 437, 442, 443, 455, 459, 465, 466, 484, 487, 499, 503, 505, 515, 522, 533, 539, 545, 547, 548, 551, 553, 558, 561, 565, 577, 578, 580, 598, 609, 623, 629, 640, 652, 655, 660, 663, 669, 672, 680, 683, 685, 697, 701, 706, 707, 712, 714, 723, 725, 732, 733, 736, 756, 758, 763, 764, 770, 775, 782, 787, 789, 794, 799, 803, 806, 815, 818, 835, 838, 875, 882, 887, 891, 893, 900, 907, 911, 916, 919, 921, 931, 932, 940, 942, 947, 949, 956, 957, 961, 975, 979, 983, 987, 995, 1003, 1009, 1015, 1024, 1032, 1041, 1051, 1057, 1068, 1073, 1076, 1077, 1082, 1086, 1097, 1103, 1107, 1119, 1136, 1145, 1151, 1154, 1156, 1160, 1183, 1185, 1197, 1198, 1199, 1216, 1220, 1225, 1226, 1229, 1235, 1237, 1239, 1240, 1252, 1253, 1257, 1263, 1265, 1266, 1279, 1281, 1282, 1285, 1292, 1293, 1301, 1307, 1312, 1313, 1314, 1317, 1320, 1323, 1324, 1329, 1334, 1339, 1351, 1354, 1356, 1358, 1361, 1364, 1365, 1371, 1378, 1381, 1384, 1385, 1386, 1408, 1410, 1416, 1445, 1452, 1454, 1463, 1464, 1469, 1480, 1481, 1482, 1486, 1491, 1493, 1501, 1503, 1504, 1513, 1515, 1519, 1520, 1522, 1530, 1535, 1547, 1549, 1551, 1556, 1557, 1558, 1569, 1578, 1584, 1586, 1591, 1599, 1625, 1635, 1636, 1640, 1643, 1648, 1652, 1656, 1660, 1667, 1668, 1669, 1670, 1683, 1694, 1701, 1714, 1735, 1737, 1740, 1741, 1742, 1746, 1747, 1749, 1750, 1753, 1754, 1760, 1761, 1767, 1770, 1771, 1772, 1778, 1781, 1785, 1790, 1794, 1795, 1796, 1809, 1824, 1826, 1827, 1829, 1831, 1832, 1852, 1860, 1861, 1865, 1866, 1869, 1872, 1885, 1888, 1892, 1894, 1899, 1902, 1908, 1915, 1918, 1919, 1920, 1923, 1924, 1928, 1929, 1931, 1942, 1949, 1950, 1953, 1954, 1955, 1961, 1963, 1975, 1978, 1979, 1987, 1989, 1999]
X075 = X[columns]
len(X075.columns)

344

In [130]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X075, y, test_size=0.2, random_state=42, stratify=y)

# Standardize the features (important for regularization methods)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Lasso

In [131]:
# Create the Lasso model
lasso = Lasso()

# Set up a grid of hyperparameters to search
param_grid = {'alpha': [0.001, 0.01, 0.1, 1.0, 10.0]}

# Use GridSearchCV to find the best hyperparameters
grid_search = GridSearchCV(lasso, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train_scaled, y_train)

# Get the best hyperparameters
best_alpha = grid_search.best_params_['alpha']

# Fit the Lasso model with the best hyperparameters on the entire training set
lasso_best = Lasso(alpha=best_alpha)
lasso_best.fit(X_train_scaled, y_train)

# Identify the selected features
selected_features_lasso_075 = X075.columns[lasso_best.coef_ != 0]

# Evaluate the model on the test set
y_pred = lasso_best.predict(X_test_scaled)
y_pred_binary = (lasso_best.predict(X_test_scaled) > 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred_binary)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)


# Print results
print("Best alpha:", best_alpha)
print("Selected Features:", selected_features_lasso_075)
print("Test Accuracy:", accuracy)
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.467e-03, tolerance: 8.667e-04
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.279e-03, tolerance: 8.974e-04
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.218e-03, tolerance: 9.231e

Best alpha: 0.1
Selected Features: Int64Index([71, 376, 390, 660, 764, 1503, 1771, 1869], dtype='int64')
Test Accuracy: 0.8461538461538461
Mean Squared Error (MSE): 0.14295113298973572
R-squared (R2): 0.3960314631183667


## SVM-RFE

In [132]:
# Create an SVM model
svm_model = SVC(kernel='linear')

# Create a pipeline with RFE and SVM
pipeline = Pipeline([
    ('feature_selection', RFE(svm_model)),
    ('classification', svm_model)
])

# Set the range of features to select
n_features_range = list(range(20, 50))  # Adjust the range based on your dataset

# Create a parameter grid
param_grid = {
    'feature_selection__n_features_to_select': n_features_range
}

# Perform cross-validated grid search
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)  # Adjust the number of splits as needed
grid_search = GridSearchCV(pipeline, param_grid=param_grid, cv=cv, scoring='accuracy')
grid_search.fit(X_train_scaled, y_train)

# Print the results
print("Best number of features:", grid_search.best_params_['feature_selection__n_features_to_select'])
print("Best cross-validated accuracy:", grid_search.best_score_)

# Use the best number of features from the grid search
n_best_features_075 = grid_search.best_params_['feature_selection__n_features_to_select']

# Create an SVM model with RFE using the best number of features
final_svm_model = SVC(kernel='linear')
final_rfe = RFE(final_svm_model, n_features_to_select=n_best_features_075)

# Fit the final model on the training set
final_rfe.fit(X_train_scaled, y_train)

# Get the selected features
selected_features_rfe_075 = X075.columns[final_rfe.support_]
# Make predictions on the test set
y_pred = final_rfe.predict(X_test_scaled)

# Compute and print the test accuracy
test_accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", test_accuracy)
print("Selected Features:", n_best_features_075)
print(f"Mean Squared Error (MSE): {mse}")

Best number of features: 30
Best cross-validated accuracy: 0.8355555555555556
Test Accuracy: 0.5384615384615384
Selected Features: 30
Mean Squared Error (MSE): 0.14295113298973572


## T=0.8

In [133]:
columns = [4, 5, 10, 17, 29, 31, 32, 34, 37, 45, 49, 50, 51, 52, 55, 65, 66, 69, 71, 78, 82, 92, 100, 106, 114, 116, 117, 123, 124, 132, 143, 150, 152, 155, 158, 159, 175, 176, 177, 187, 191, 196, 205, 208, 223, 224, 227, 228, 233, 242, 244, 247, 250, 251, 257, 259, 260, 261, 262, 263, 267, 268, 270, 273, 277, 280, 284, 285, 301, 303, 306, 314, 316, 336, 338, 340, 347, 348, 349, 353, 356, 383, 384, 385, 398, 403, 404, 410, 412, 418, 420, 422, 424, 426, 437, 443, 455, 456, 459, 464, 466, 473, 484, 487, 490, 492, 497, 501, 503, 507, 513, 514, 515, 521, 522, 526, 533, 539, 545, 546, 551, 553, 556, 557, 558, 559, 564, 565, 576, 577, 578, 580, 586, 588, 596, 598, 600, 602, 605, 609, 621, 623, 624, 627, 629, 635, 640, 643, 648, 649, 652, 653, 655, 660, 662, 663, 669, 672, 677, 680, 681, 683, 685, 689, 694, 695, 697, 701, 706, 707, 710, 714, 719, 721, 722, 723, 725, 733, 736, 741, 748, 749, 756, 758, 770, 776, 778, 782, 783, 787, 794, 798, 799, 800, 801, 803, 806, 813, 818, 827, 830, 831, 835, 838, 844, 852, 853, 855, 865, 875, 878, 884, 891, 893, 900, 903, 905, 907, 910, 911, 915, 917, 919, 921, 923, 925, 927, 930, 931, 932, 940, 942, 947, 949, 953, 956, 957, 962, 963, 965, 969, 973, 975, 983, 986, 987, 993, 995, 1009, 1013, 1015, 1021, 1023, 1024, 1033, 1034, 1036, 1041, 1049, 1050, 1052, 1057, 1063, 1073, 1076, 1077, 1082, 1086, 1088, 1093, 1097, 1103, 1107, 1113, 1119, 1135, 1145, 1146, 1148, 1156, 1163, 1170, 1172, 1179, 1185, 1188, 1197, 1199, 1202, 1206, 1211, 1212, 1220, 1225, 1226, 1235, 1237, 1239, 1240, 1244, 1247, 1253, 1273, 1281, 1282, 1285, 1290, 1294, 1295, 1298, 1300, 1301, 1303, 1306, 1307, 1310, 1311, 1313, 1314, 1316, 1317, 1320, 1322, 1323, 1324, 1326, 1329, 1334, 1339, 1342, 1347, 1348, 1349, 1354, 1356, 1358, 1361, 1364, 1371, 1373, 1374, 1377, 1378, 1380, 1381, 1384, 1385, 1386, 1398, 1401, 1405, 1407, 1410, 1411, 1413, 1415, 1416, 1423, 1428, 1436, 1438, 1442, 1445, 1451, 1452, 1454, 1463, 1464, 1469, 1472, 1473, 1480, 1481, 1482, 1484, 1492, 1493, 1494, 1495, 1501, 1503, 1504, 1506, 1513, 1515, 1520, 1521, 1528, 1530, 1534, 1535, 1536, 1542, 1547, 1549, 1551, 1555, 1556, 1557, 1558, 1559, 1569, 1570, 1577, 1581, 1582, 1584, 1586, 1588, 1591, 1596, 1599, 1605, 1606, 1607, 1612, 1613, 1619, 1624, 1625, 1630, 1635, 1636, 1640, 1643, 1648, 1650, 1654, 1656, 1658, 1660, 1667, 1668, 1669, 1670, 1672, 1673, 1675, 1680, 1681, 1687, 1694, 1698, 1700, 1704, 1707, 1708, 1713, 1714, 1729, 1735, 1737, 1740, 1741, 1742, 1745, 1746, 1747, 1748, 1749, 1754, 1760, 1762, 1763, 1767, 1770, 1773, 1775, 1778, 1781, 1784, 1785, 1786, 1788, 1790, 1794, 1795, 1798, 1809, 1810, 1812, 1813, 1816, 1819, 1821, 1822, 1824, 1827, 1835, 1844, 1849, 1852, 1856, 1860, 1861, 1865, 1866, 1869, 1871, 1872, 1879, 1885, 1887, 1891, 1892, 1894, 1898, 1900, 1901, 1902, 1904, 1905, 1908, 1912, 1919, 1920, 1923, 1924, 1927, 1928, 1929, 1931, 1933, 1934, 1937, 1940, 1942, 1943, 1949, 1950, 1953, 1954, 1957, 1962, 1963, 1971, 1975, 1978, 1979, 1981, 1984, 1986, 1987, 1989, 1990, 1992, 1995, 1999]
X08 = X[columns]
len(X08.columns)

548

In [134]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X08, y, test_size=0.2, random_state=42, stratify=y)

# Standardize the features (important for regularization methods)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [135]:
# Create the Lasso model
lasso = Lasso()

# Set up a grid of hyperparameters to search
param_grid = {'alpha': [0.001, 0.01, 0.1, 1.0, 10.0]}

# Use GridSearchCV to find the best hyperparameters
grid_search = GridSearchCV(lasso, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train_scaled, y_train)

# Get the best hyperparameters
best_alpha = grid_search.best_params_['alpha']

# Fit the Lasso model with the best hyperparameters on the entire training set
lasso_best = Lasso(alpha=best_alpha)
lasso_best.fit(X_train_scaled, y_train)

# Identify the selected features
selected_features_lasso_08 = X08.columns[lasso_best.coef_ != 0]

# Evaluate the model on the test set
y_pred = lasso_best.predict(X_test_scaled)
y_pred_binary = (lasso_best.predict(X_test_scaled) > 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred_binary)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)


# Print results
print("Best alpha:", best_alpha)
print("Selected Features:", selected_features_lasso_08)
print("Test Accuracy:", accuracy)
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.207e-03, tolerance: 8.667e-04
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.489e-03, tolerance: 8.974e-04
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.947e-03, tolerance: 9.231e

Best alpha: 0.1
Selected Features: Int64Index([106, 244, 280, 285, 426, 443, 492, 801, 1770, 1869, 1872], dtype='int64')
Test Accuracy: 0.7692307692307693
Mean Squared Error (MSE): 0.14451984652266672
R-squared (R2): 0.38940364844173325


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.298e-03, tolerance: 8.400e-04
  model = cd_fast.enet_coordinate_descent(


## SVM-RFE

In [136]:
# Create an SVM model
svm_model = SVC(kernel='linear')

# Create a pipeline with RFE and SVM
pipeline = Pipeline([
    ('feature_selection', RFE(svm_model)),
    ('classification', svm_model)
])

# Set the range of features to select
n_features_range = list(range(20, 50))  # Adjust the range based on your dataset

# Create a parameter grid
param_grid = {
    'feature_selection__n_features_to_select': n_features_range
}

# Perform cross-validated grid search
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)  # Adjust the number of splits as needed
grid_search = GridSearchCV(pipeline, param_grid=param_grid, cv=cv, scoring='accuracy')
grid_search.fit(X_train_scaled, y_train)

# Print the results
print("Best number of features:", grid_search.best_params_['feature_selection__n_features_to_select'])
print("Best cross-validated accuracy:", grid_search.best_score_)

# Use the best number of features from the grid search
n_best_features_08 = grid_search.best_params_['feature_selection__n_features_to_select']

# Create an SVM model with RFE using the best number of features
final_svm_model = SVC(kernel='linear')
final_rfe = RFE(final_svm_model, n_features_to_select=n_best_features_08)

# Fit the final model on the training set
final_rfe.fit(X_train_scaled, y_train)
# Get the selected features
selected_features_rfe_08 = X08.columns[final_rfe.support_]
# Make predictions on the test set
y_pred = final_rfe.predict(X_test_scaled)

# Compute and print the test accuracy
test_accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", test_accuracy)
print("Selected Features:", n_best_features_08)
print(f"Mean Squared Error (MSE): {mse}")

Best number of features: 31
Best cross-validated accuracy: 0.8133333333333335
Test Accuracy: 0.5384615384615384
Selected Features: 31
Mean Squared Error (MSE): 0.14451984652266672


# Classification

## without MIDS

## Lasso

In [137]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Create the Lasso model
lasso = Lasso()

# Set up a grid of hyperparameters to search
param_grid = {'alpha': [0.001, 0.01, 0.1, 1.0, 10.0]}

# Use GridSearchCV to find the best hyperparameters
grid_search = GridSearchCV(lasso, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_alpha = grid_search.best_params_['alpha']

# Fit the Lasso model with the best hyperparameters on the entire training set
lasso_best = Lasso(alpha=best_alpha)
lasso_best.fit(X_train, y_train)

# Identify the selected features
selected_features_lasso = X.columns[lasso_best.coef_ != 0]

# Evaluate the model on the test set
y_pred = lasso_best.predict(X_test)
y_pred_binary = (lasso_best.predict(X_test) > 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred_binary)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)


# Print results
print("Best alpha:", best_alpha)
print("Selected Features:", selected_features_lasso)
print("Test Accuracy:", accuracy)
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.495e-03, tolerance: 8.667e-04
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.466e-03, tolerance: 8.974e-04
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.084e-03, tolerance: 9.231e

Best alpha: 10.0
Selected Features: Int64Index([   2,    3,    4,    8,   13,   15,   33,   35,   42,   48,   68,
             114,  118,  123,  158,  163,  268,  270,  316,  414,  806,  821,
             877, 1023, 1324, 1377, 1726, 1790, 1809],
           dtype='int64')
Test Accuracy: 0.8461538461538461
Mean Squared Error (MSE): 0.14452638490997066
R-squared (R2): 0.38937602375537406


### SVM_RFE

In [138]:
# Create an SVM model
svm_model = SVC(kernel='linear')

# Create a pipeline with RFE and SVM
pipeline = Pipeline([
    ('feature_selection', RFE(svm_model)),
    ('classification', svm_model)
])

# Set the range of features to select
n_features_range = list(range(20, 50))  # Adjust the range based on your dataset

# Create a parameter grid
param_grid = {
    'feature_selection__n_features_to_select': n_features_range
}

# Perform cross-validated grid search
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)  # Adjust the number of splits as needed
grid_search = GridSearchCV(pipeline, param_grid=param_grid, cv=cv, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Print the results
print("Best number of features:", grid_search.best_params_['feature_selection__n_features_to_select'])
print("Best cross-validated accuracy:", grid_search.best_score_)

# Use the best number of features from the grid search
n_best_features_08 = grid_search.best_params_['feature_selection__n_features_to_select']

# Create an SVM model with RFE using the best number of features
final_svm_model = SVC(kernel='linear')
final_rfe = RFE(final_svm_model, n_features_to_select=n_best_features_08)

# Fit the final model on the training set
final_rfe.fit(X_train, y_train)
# Get the selected features
selected_features_rfe = X.columns[final_rfe.support_]
# Make predictions on the test set
y_pred = final_rfe.predict(X_test)

# Compute and print the test accuracy
test_accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", test_accuracy)
print("Selected Features:", n_best_features_08)
print(f"Mean Squared Error (MSE): {mse}")

Best number of features: 24
Best cross-validated accuracy: 0.8555555555555555
Test Accuracy: 0.6923076923076923
Selected Features: 24
Mean Squared Error (MSE): 0.14452638490997066


### SVM

In [139]:
# Import necessary libraries
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import numpy as np

X_train_lasso = X_train[selected_features_lasso]
X_test_lasso = X_test[selected_features_lasso]
# Define the SVM Classifier
svm_classifier = SVC()

# Define hyperparameters to tune
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_lasso, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the SVM Classifier with the best parameters
best_svm_classifier = SVC(**best_params)
best_svm_classifier.fit(X_train_lasso, y_train)

# Predict on the test set
y_pred = best_svm_classifier.predict(X_test_lasso)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[4 1]
 [1 7]]

Evaluation Metrics:
Accuracy: 0.8462
Precision: 0.8750
Recall: 0.8750
F1 Score: 0.8750

Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.80      0.80         5
           1       0.88      0.88      0.88         8

    accuracy                           0.85        13
   macro avg       0.84      0.84      0.84        13
weighted avg       0.85      0.85      0.85        13



### Random Forest

In [140]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report



# Define the Random Forest Classifier
rf_classifier = RandomForestClassifier()

# Define hyperparameters to tune
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_lasso, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the Random Forest Classifier with the best parameters
best_rf_classifier = RandomForestClassifier(**best_params)
best_rf_classifier.fit(X_train_lasso, y_train)

# Predict on the test set
y_pred = best_rf_classifier.predict(X_test_lasso)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[2 3]
 [2 6]]

Evaluation Metrics:
Accuracy: 0.6154
Precision: 0.6667
Recall: 0.7500
F1 Score: 0.7059

Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.40      0.44         5
           1       0.67      0.75      0.71         8

    accuracy                           0.62        13
   macro avg       0.58      0.57      0.58        13
weighted avg       0.60      0.62      0.61        13



## SVM RFE

### SVM

In [141]:
# Import necessary libraries
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import numpy as np

X_train_rfe = X_train[selected_features_rfe]
X_test_rfe = X_test[selected_features_rfe]
# Define the SVM Classifier
svm_classifier = SVC()

# Define hyperparameters to tune
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_rfe, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the SVM Classifier with the best parameters
best_svm_classifier = SVC(**best_params)
best_svm_classifier.fit(X_train_rfe, y_train)

# Predict on the test set
y_pred = best_svm_classifier.predict(X_test_rfe)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[3 2]
 [2 6]]

Evaluation Metrics:
Accuracy: 0.6923
Precision: 0.7500
Recall: 0.7500
F1 Score: 0.7500

Classification Report:
              precision    recall  f1-score   support

           0       0.60      0.60      0.60         5
           1       0.75      0.75      0.75         8

    accuracy                           0.69        13
   macro avg       0.68      0.68      0.68        13
weighted avg       0.69      0.69      0.69        13



### Random Forest

In [142]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report



# Define the Random Forest Classifier
rf_classifier = RandomForestClassifier()

# Define hyperparameters to tune
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_rfe, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the Random Forest Classifier with the best parameters
best_rf_classifier = RandomForestClassifier(**best_params)
best_rf_classifier.fit(X_train_rfe, y_train)

# Predict on the test set
y_pred = best_rf_classifier.predict(X_test_rfe)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[2 3]
 [2 6]]

Evaluation Metrics:
Accuracy: 0.6154
Precision: 0.6667
Recall: 0.7500
F1 Score: 0.7059

Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.40      0.44         5
           1       0.67      0.75      0.71         8

    accuracy                           0.62        13
   macro avg       0.58      0.57      0.58        13
weighted avg       0.60      0.62      0.61        13



## With MIDS

## T = 0.7

## Lasso

In [143]:
X1 = X[selected_features_lasso_07]
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.2, random_state=42, stratify=y)

### SVM

In [144]:
# Import necessary libraries
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import numpy as np


# Define the SVM Classifier
svm_classifier = SVC()

# Define hyperparameters to tune
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the SVM Classifier with the best parameters
best_svm_classifier = SVC(**best_params)
best_svm_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_svm_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[3 2]
 [3 5]]

Evaluation Metrics:
Accuracy: 0.6154
Precision: 0.7143
Recall: 0.6250
F1 Score: 0.6667

Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.60      0.55         5
           1       0.71      0.62      0.67         8

    accuracy                           0.62        13
   macro avg       0.61      0.61      0.61        13
weighted avg       0.63      0.62      0.62        13



### Random forest

In [145]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report



# Define the Random Forest Classifier
rf_classifier = RandomForestClassifier()

# Define hyperparameters to tune
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the Random Forest Classifier with the best parameters
best_rf_classifier = RandomForestClassifier(**best_params)
best_rf_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_rf_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[3 2]
 [2 6]]

Evaluation Metrics:
Accuracy: 0.6923
Precision: 0.7500
Recall: 0.7500
F1 Score: 0.7500

Classification Report:
              precision    recall  f1-score   support

           0       0.60      0.60      0.60         5
           1       0.75      0.75      0.75         8

    accuracy                           0.69        13
   macro avg       0.68      0.68      0.68        13
weighted avg       0.69      0.69      0.69        13



## SVM-RFE

In [146]:
X1 = X[selected_features_rfe_07]
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.2, random_state=42, stratify=y)

### SVM

In [147]:
# Import necessary libraries
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import numpy as np


# Define the SVM Classifier
svm_classifier = SVC()

# Define hyperparameters to tune
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the SVM Classifier with the best parameters
best_svm_classifier = SVC(**best_params)
best_svm_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_svm_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[3 2]
 [1 7]]

Evaluation Metrics:
Accuracy: 0.7692
Precision: 0.7778
Recall: 0.8750
F1 Score: 0.8235

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.78      0.88      0.82         8

    accuracy                           0.77        13
   macro avg       0.76      0.74      0.75        13
weighted avg       0.77      0.77      0.76        13



### Random Forest

In [148]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report



# Define the Random Forest Classifier
rf_classifier = RandomForestClassifier()

# Define hyperparameters to tune
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the Random Forest Classifier with the best parameters
best_rf_classifier = RandomForestClassifier(**best_params)
best_rf_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_rf_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[4 1]
 [2 6]]

Evaluation Metrics:
Accuracy: 0.7692
Precision: 0.8571
Recall: 0.7500
F1 Score: 0.8000

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.80      0.73         5
           1       0.86      0.75      0.80         8

    accuracy                           0.77        13
   macro avg       0.76      0.78      0.76        13
weighted avg       0.78      0.77      0.77        13



### T = 0.75

## Lasso

In [149]:
X2 = X[selected_features_lasso_075]
X_train, X_test, y_train, y_test = train_test_split(X2, y, test_size=0.2, random_state=42, stratify=y)

### SVM

In [150]:
# Import necessary libraries
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import numpy as np


# Define the SVM Classifier
svm_classifier = SVC()

# Define hyperparameters to tune
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the SVM Classifier with the best parameters
best_svm_classifier = SVC(**best_params)
best_svm_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_svm_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[3 2]
 [1 7]]

Evaluation Metrics:
Accuracy: 0.7692
Precision: 0.7778
Recall: 0.8750
F1 Score: 0.8235

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.78      0.88      0.82         8

    accuracy                           0.77        13
   macro avg       0.76      0.74      0.75        13
weighted avg       0.77      0.77      0.76        13



### Random Forest

In [151]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report



# Define the Random Forest Classifier
rf_classifier = RandomForestClassifier()

# Define hyperparameters to tune
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the Random Forest Classifier with the best parameters
best_rf_classifier = RandomForestClassifier(**best_params)
best_rf_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_rf_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[4 1]
 [2 6]]

Evaluation Metrics:
Accuracy: 0.7692
Precision: 0.8571
Recall: 0.7500
F1 Score: 0.8000

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.80      0.73         5
           1       0.86      0.75      0.80         8

    accuracy                           0.77        13
   macro avg       0.76      0.78      0.76        13
weighted avg       0.78      0.77      0.77        13



## SVM_RFE

In [152]:
X2 = X[selected_features_rfe_075]
X_train, X_test, y_train, y_test = train_test_split(X2, y, test_size=0.2, random_state=42, stratify=y)

### SVM

In [153]:
# Import necessary libraries
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import numpy as np


# Define the SVM Classifier
svm_classifier = SVC()

# Define hyperparameters to tune
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the SVM Classifier with the best parameters
best_svm_classifier = SVC(**best_params)
best_svm_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_svm_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[2 3]
 [1 7]]

Evaluation Metrics:
Accuracy: 0.6923
Precision: 0.7000
Recall: 0.8750
F1 Score: 0.7778

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.40      0.50         5
           1       0.70      0.88      0.78         8

    accuracy                           0.69        13
   macro avg       0.68      0.64      0.64        13
weighted avg       0.69      0.69      0.67        13



### Random Forest

In [154]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report



# Define the Random Forest Classifier
rf_classifier = RandomForestClassifier()

# Define hyperparameters to tune
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the Random Forest Classifier with the best parameters
best_rf_classifier = RandomForestClassifier(**best_params)
best_rf_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_rf_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[3 2]
 [1 7]]

Evaluation Metrics:
Accuracy: 0.7692
Precision: 0.7778
Recall: 0.8750
F1 Score: 0.8235

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.78      0.88      0.82         8

    accuracy                           0.77        13
   macro avg       0.76      0.74      0.75        13
weighted avg       0.77      0.77      0.76        13



### T = 0.8

## Lasso

In [155]:
X3 = X[selected_features_lasso_08]
X_train, X_test, y_train, y_test = train_test_split(X3, y, test_size=0.2, random_state=42, stratify=y)

### SVM

In [156]:
# Import necessary libraries
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import numpy as np


# Define the SVM Classifier
svm_classifier = SVC()

# Define hyperparameters to tune
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the SVM Classifier with the best parameters
best_svm_classifier = SVC(**best_params)
best_svm_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_svm_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[3 2]
 [0 8]]

Evaluation Metrics:
Accuracy: 0.8462
Precision: 0.8000
Recall: 1.0000
F1 Score: 0.8889

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.60      0.75         5
           1       0.80      1.00      0.89         8

    accuracy                           0.85        13
   macro avg       0.90      0.80      0.82        13
weighted avg       0.88      0.85      0.84        13



### Random Forest

In [157]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report



# Define the Random Forest Classifier
rf_classifier = RandomForestClassifier()

# Define hyperparameters to tune
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the Random Forest Classifier with the best parameters
best_rf_classifier = RandomForestClassifier(**best_params)
best_rf_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_rf_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[3 2]
 [2 6]]

Evaluation Metrics:
Accuracy: 0.6923
Precision: 0.7500
Recall: 0.7500
F1 Score: 0.7500

Classification Report:
              precision    recall  f1-score   support

           0       0.60      0.60      0.60         5
           1       0.75      0.75      0.75         8

    accuracy                           0.69        13
   macro avg       0.68      0.68      0.68        13
weighted avg       0.69      0.69      0.69        13



## SVM_RFE

In [158]:
X3 = X[selected_features_rfe_08]
X_train, X_test, y_train, y_test = train_test_split(X3, y, test_size=0.2, random_state=42, stratify=y)

### SVM

In [159]:
# Import necessary libraries
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import numpy as np


# Define the SVM Classifier
svm_classifier = SVC()

# Define hyperparameters to tune
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the SVM Classifier with the best parameters
best_svm_classifier = SVC(**best_params)
best_svm_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_svm_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[3 2]
 [1 7]]

Evaluation Metrics:
Accuracy: 0.7692
Precision: 0.7778
Recall: 0.8750
F1 Score: 0.8235

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.78      0.88      0.82         8

    accuracy                           0.77        13
   macro avg       0.76      0.74      0.75        13
weighted avg       0.77      0.77      0.76        13



### Random Forest

In [160]:
# Import necessary libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report



# Define the Random Forest Classifier
rf_classifier = RandomForestClassifier()

# Define hyperparameters to tune
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Use GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Train the Random Forest Classifier with the best parameters
best_rf_classifier = RandomForestClassifier(**best_params)
best_rf_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = best_rf_classifier.predict(X_test)

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print evaluation metrics
accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
precision = conf_matrix[1, 1] / np.sum(conf_matrix[:, 1])
recall = conf_matrix[1, 1] / np.sum(conf_matrix[1, :])
f1_score = 2 * (precision * recall) / (precision + recall)

print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")

# Optionally, you can print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[3 2]
 [1 7]]

Evaluation Metrics:
Accuracy: 0.7692
Precision: 0.7778
Recall: 0.8750
F1 Score: 0.8235

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.78      0.88      0.82         8

    accuracy                           0.77        13
   macro avg       0.76      0.74      0.75        13
weighted avg       0.77      0.77      0.76        13

